version: "3.9"
services:
  nginx:
    container_name: reverse-proxy
    image: ubuntu/nginx:1.18-22.04_beta
    restart: always
    volumes:
      - "./html:/var/www/html"
      - "./conf/ngnix.conf:/etc/nginx/nginx.conf"
      - "./conf/default.api.conf:/etc/nginx/sites-available/default"
      - "./conf/mime.types:/etc/nginx/mime.types"
      - "./logs:/var/log/nginx"
      - "./ssl:/etc/ssl"
    environment:
      - TZ:UTC-4
    ports:
      - "80:80"
      - "443:443"
