# Configuración de servidores de esta maquina. Actualmente son 3 dominios
server {
    listen 80;
    listen [::]:80;
    server_name logia.buenaventuracadiz.cl;
    return 301 https://$host$request_uri;

    location / {
      try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name link.buenaventuracadiz.cl;
    return 301 https://docs.google.com/spreadsheets/d/1w9ggYx0n51p6lxYh0yLsmKpcmaKYc7UTPxxIpk1zQt8/edit?gid=585366572#gid=585366572;

    location /programa {
      return 301 https://docs.google.com/spreadsheets/d/1w9ggYx0n51p6lxYh0yLsmKpcmaKYc7UTPxxIpk1zQt8/edit?gid=585366572#gid=585366572;
    }
}

