server {
    listen 443          ssl;
    listen [::]:443     ssl;
    server_name         api.jonna.cl;

    ssl_certificate     /etc/ssl/ssl_jonna_cl.crt;
    ssl_certificate_key /etc/ssl/ssl_jonna_cl.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    error_log           /var/log/nginx/api_jonna.error.log;
    access_log          /var/log/nginx/api_jonna.access.log detail; 

    error_page 500 502 503 504 /error.html;      
    error_page 404 /no_found.html;

    location = /error.html {
        root /var/www/html;
        internal;
    }

    location = /no_found.html {
        root /var/www/html;
        internal;
    }

    location = /favicon.ico {
        root /var/www/html/jonnattan;
    }

    location / {
        proxy_pass http://api-jonnattan:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
}