
server {
    listen      80;
    listen      [::]:80;
    server_name www.jonna.cl;
    return 301  https://$host$request_uri;

    location / {
      try_files $uri $uri/ =404;
    }
}

server {
    listen 443          ssl;
    listen [::]:443     ssl;
    server_name         www.jonna.cl;

    ssl_certificate     /etc/ssl/www_jonna_cl.crt;
    ssl_certificate_key /etc/ssl/www_jonna_cl.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    error_log           /var/log/nginx/jonna.cl.error.log;
    access_log          /var/log/nginx/jonna.cl.access.log detail; 

    error_page          500 502 503 504 /error.html;      
    error_page          404 /no_found.html;

    root                /var/www/html;
    index               index.html index.htm index.nginx-debian.html;

    location = /error.html {
        root /var/www/html;
        internal;
    }

    location = /no_found.html {
        root /var/www/html;
        internal;
    }

    location = /favicon.ico {
        root /var/www/html/jonnattan;
    }

}

server {
    listen      80;
    listen      [::]:80;
    server_name api.jonna.cl;
    return 301  https://$host$request_uri;

    location / {
      try_files $uri $uri/ =404;
    }
}

server {
    listen 443          ssl;
    listen [::]:443     ssl;
    server_name         api.jonna.cl;

    ssl_certificate     /etc/ssl/api_jonna_cl.crt;
    ssl_certificate_key /etc/ssl/api_jonna_cl.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    error_log           /var/log/nginx/api_jonna_cl.error.log;
    access_log          /var/log/nginx/api_jonna_cl.access.log detail; 

    error_page 500 502 503 504 /error.html;      
    error_page 404 /no_found.html;

    root                /var/www/html;
    index               index.html index.htm index.nginx-debian.html;

    location = /error.html {
        root /var/www/html;
        internal;
    }

    location = /no_found.html {
        root /var/www/html;
        internal;
    }

    location = /favicon.ico {
        root /var/www/html/jonnattan;
    }

    location / {
        proxy_pass_request_headers  on;
        proxy_pass          http://api-jonnattan:8085;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;
        proxy_set_header    X-Forwarded-Host $host;
        proxy_set_header    X-Forwarded-Port $server_port;
    }

}