# Default server configuration for Jonnattan
#

server {
    listen 80;
    listen [::]:80;
    server_name logia.buenaventura.cl;
    return 301 https://$host$request_uri;

    #location /.well-known/pki-validation/80B63C551F93D5C4F47CBD50F451BA4D.txt {
    #  root /var/www/html;
    #  index .well-known/pki-validation/80B63C551F93D5C4F47CBD50F451BA4D.txt;
    #}

    #location / {
    #  try_files $uri $uri/ =404;
    #}
}

server {
      listen 443          ssl;
      listen [::]:443     ssl;
      server_name         logia.buenaventura.cl;
      ssl_certificate     /etc/ssl/buenaventura.com.crt;
      ssl_certificate_key /etc/ssl/buenaventura.com.key;
      ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
      error_log           /var/log/nginx/logia.error.log;
      access_log          /var/log/nginx/logia.access.log; 
      root                /var/www/html;
      index               index.html index.htm index.nginx-debian.html;

      # En caso de matenimiento tipicamente aparece el error bad wategay http 502
      # y cuando se baja el contenedor del website automaticamente se muestra esto

      error_page 500 502 503 504 /error.html;

      location = /error.html {
            root /var/www/html;
            internal;
      }

      location /favicon.ico {
        root /var/www/html;
        index /favicon.ico;
      }

       location /checksystem {
        proxy_pass  http://logia-server:58085/checksystem;
      }

      location ^~ /bcp {
        proxy_pass  http://logia-server:58085/bcp;
        proxy_pass_request_headers  on;
        proxy_set_header            Host $host;
        proxy_set_header            X-Real-IP  $remote_addr;
        proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header            X-Forwarded-Proto https;
        proxy_set_header            X-Forwarded-Host $host;
      }

      location /static {
        proxy_pass  http://logia-server:58085/static;
      }
}
